# Site settings
title: PERINFO 2013 Programming Class
email: dimasahmad@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/training/" # the subpath of your site, e.g. /blog/
url: "http://perpusinfo.github.io" # the base hostname & protocol for your site
twitter_username: perinfo2013
github_username:  perpusinfo

# Build settings
markdown: kramdown
highlighter: pygments
